#pragma once

#define RLOGGER_DEVICE 0x8000

#define IOCTL_RLOGGER_SET_TARGET_PID CTL_CODE(RLOGGER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_RLOGGER_STOP_LOGGING CTL_CODE(RLOGGER_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)